name: Reuse old wheel if possible

description:
  Reuse old wheel if possible

inputs:
  build-environment:
    description: Build environment
    required: true
  workflow-id:
    description: Workflow ID
    required: true
  github-token:
    description: GitHub token
    required: true

outputs:
  reuse:
    description: Whether the wheel is reused or not
    value: ${{ steps.check-file-changes.outputs.build }}

runs:
  using: composite

  steps:
    # Check out pytorch with fetch depth 0
    - name: Check file changes
      id: check-file-changes
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        set -x
        python3 .github/actions/check-old-whl/reuse_old_whl.py \
          --build-environment "${{ inputs.build-environment }}" \
          --workflow-id "${{ inputs.workflow-id }}"
